services:
  mc-server:
    build:
      context: .
      args:
        SERVER_JAR_URL: ${SERVER_JAR_URL}
    image: mc-server:latest
    container_name: mc-server
    env_file:
      - .env
    environment:
      - EULA=${EULA}
      - MAX_RAM=${MAX_RAM}
      - MIN_RAM=${MIN_RAM}
    ports:
      - "${HOST_PORT:-25565}:25565"
    volumes:
      - ./data:/data   # nur Spielstände
    restart: unless-stopped